export enum OrderBy {
    DEFAULT,
    LARGEST_LOAN_AMOUNT,
    SMALLEST_LOAN_AMOUNT,
    FEWEST_NUMBER_OF_INSTALLMENTS,
    BIGGEST_NUMBER_OF_INSTALLMENTS,
    NEWEST,
    OLDEST,
    CLOSING_SOONEST,
}
