import {Offer} from './offersAPI.types';

/**
 * Main auction object that will be used
 * to display informations about certain auction
 */
export interface Auction {
    /**
     * Time of creation of auction by borrower
     *
     * Represented as integer number of seconds from 01.01.1970
     */
    beginDate: number;
    /**
     * Scheduled end time for auction
     *
     * Represented as integer number of seconds from 01.01.1970
     */
    endDate: number;
    /**
     * Unique id for auction object
     *
     * Represented as positive integer
     */
    id: number;
    /**
     * Amount of money that borrower needs to
     * lend
     *
     * Represented as floating point number of defined currency
     */
    loanAmount: number;
    /**
     * Number of installments in auction,
     * specified by borrower at the time of
     * auction creation
     *
     * Represented as integer greater than 0
     */
    numberOfInstallments: number;
    /**
     * Brief description of auction about
     * reason of creating auction and
     * potential benefit for borrower
     *
     * Represented as string with more than 5 characters
     */
    description: string;
    /**
     * List of offers generated by lenders for this auction
     *
     * Represented as list of {@link Offer} objects
     */
    offers: Offer[];
}

/**
 * Auction object used mainly in communication with
 * api. Specifies required fields during auction
 * creation process
 */
export interface AuctionDTO {
    /**
     * Scheduled end time for auction
     *
     * Represented as integer number of seconds from 01.01.1970
     */
    endDate: string;
    /**
     * Amount of money that borrower needs to
     * lend
     *
     * Represented as floating point number of defined currency
     */
    loanAmount: number;
    /**
     * Number of installments in auction,
     * specified by borrower at the time of
     * auction creation
     *
     * Represented as integer greater than 0
     */
    numberOfInstallments: number;
    /**
     * Brief description of auction about
     * reason of creating auction and
     * potential benefit for borrower
     *
     * Represented as string with more than 5 characters
     */
    description: string;
}
